#!/bin/bash
echo "$CBUSER"
IMAGE="patt1293/chaturbae-client:latest"
ls -alh
git checkout master
cd cb_client
touch docker-compose-generated.yml
dOut=""
sample=$(node get_18_us_list.js)
#sample='[{"name":"foo"},{"name":"bar"}]'
for row in $(echo "${sample}" | jq -r '.[] | @base64'); do
    _jq() {
     echo ${row} | base64 --decode | jq -r ${1}
    }
    uName = $(_jq '.username')
    sName = $(_jq '.sanitized_nick')
	dTemplate=$(cat docker-compose.template | sed -e "s|##IMAGE##|$IMAGE|g" -e "s|##CB_USERNAME##|$uName|g" -e "s|##CLEAN_USERNAME##|$sName|g")
   echo $(_jq '.username')
done
#while read p; do
#    nameMinusWorker=$(echo $p | sed 's|-worker||g')
#    nameReplaceDash=$(echo $nameMinusWorker | sed 's|-|_|g')
#    dTemplate=$(cat docker-compose.template | sed -e "s|##IMAGE##|$IMAGE|g" -e "s|##CB_USERNAME##|$nameReplaceDash|g" -e "s|##CLEAN_USERNAME##|$nameMinusWorker|g")
#    #echo $nameReplaceDash
#    dOut="$dOut\n  $dTemplate"
#done < base_list.txt
    printf "version: '2'\nservices:$dOut" > docker-compose-generated.yml
    cat docker-compose-generated.yml
#cd ../
#git add cb_client/docker-compose-generated.yml
#git commit -m 'autogenerated docker-compose file by jenkins'
#git push https://patrick-hudson:f9dfbef213ba9bfed93c9de4b9af97c19a445b19@github.com/patrick-hudson/chaturbae.git
